### ISSUE TITLE
Metal Compiler Error

### ISSUE THREAD

**Issue by AQUArchitect** [Unii/Shaders-iOS#1]
I got this error. Can you take a look? Thank you

![screen shot 2015-02-26 at 2 58 44 pm](https://cloud.githubusercontent.com/assets/8365795/6403967/128b75b2-bdc8-11e4-8125-529585d224dc.png)

**Comment by jcampbell05** [comment]
It looks like your trying to build for the simulator, you need to build to a iOS Device when building this framework. I'll update our tutorial and readme to reflect this, thanks.

**Comment by AQUArchitect** [comment]
I might misunderstand that your tutorial was a workaround to make your Metal work on Simulator. Thanks.
